### ISSUE TITLE
Error returned while running miningrate.py

### ISSUE THREAD

**Issue by ivianoo** [JanKalin/zcutils#3]
![screenshot from 2016-10-29 02-03-27](https://cloud.githubusercontent.com/assets/22801868/19822311/455dff38-9d7c-11e6-98ff-72e1c609d4e2.png)
This is the error returned after running so you need to address the issue plz

**Comment by JanKalin** [comment]
That happens if there are no mined coins. Instead of crashing, the program now prints out a message.  Commit: https://github.com/JanKalin/zcutils/commit/6ec8b3c8e59703ce121ee64e275a0e1bbe83028e
